import {
  AbsoluteFill, Audio, interpolate, Sequence, staticFile,
  useCurrentFrame, useVideoConfig,
} from "remotion";
import data from "./data.json";

/**
 * One scene per authored slide. Nothing here invents content: every word on screen came
 * out of the storyboard, which is what makes the render checkable against the spec.
 *
 * The layout branches on aspect ratio rather than scaling. A 9:16 frame is not a squeezed
 * 16:9 — the safe area is different, the type has to be larger relative to the frame, and
 * the bottom fifth is covered by platform UI on most apps. Compose for it or lose the
 * caption behind a like button.
 */
const RED = "#EC1C24";
const INK = "#0A0A0C";

/** Burned-in caption — most viewers watch muted; this is the primary channel. */
const Caption: React.FC<{ text: string; vertical: boolean }> = ({ text, vertical }) => (
  <div
    style={{
      position: "absolute",
      left: vertical ? "6%" : "10%",
      right: vertical ? "6%" : "10%",
      // Stay above platform UI on 9:16 (bottom fifth reserved).
      bottom: vertical ? "28%" : "8%",
      backgroundColor: "rgba(0,0,0,0.72)",
      color: "#fff",
      fontSize: vertical ? 36 : 32,
      lineHeight: 1.35,
      fontWeight: 600,
      padding: vertical ? "14px 18px" : "12px 20px",
      borderRadius: 8,
      textAlign: "center",
      fontFamily: "Tahoma, Verdana, sans-serif",
    }}
  >
    {text}
  </div>
);

const Slide: React.FC<{ direction: string; onScreen: string | null }> = ({
  direction, onScreen,
}) => {
  const frame = useCurrentFrame();
  const { width, height } = useVideoConfig();
  const vertical = height > width;
  const caption = onScreen ?? direction;

  // Ease in over 8 frames. One focal move per scene — see the brand book's motion rules.
  const enter = interpolate(frame, [0, 8], [0, 1], {
    extrapolateLeft: "clamp", extrapolateRight: "clamp",
  });
  const lift = interpolate(frame, [0, 8], [18, 0], {
    extrapolateLeft: "clamp", extrapolateRight: "clamp",
  });

  return (
    <AbsoluteFill
      style={{
        backgroundColor: INK,
        justifyContent: vertical ? "flex-start" : "center",
        // 9:16: keep everything out of the bottom fifth, where the platform UI sits.
        padding: vertical ? "18% 8% 26%" : "0 12%",
        fontFamily: "Tahoma, Verdana, sans-serif",
      }}
    >
      <div style={{ opacity: enter, transform: `translateY(${lift}px)` }}>
        {onScreen ? (
          <div
            style={{
              color: "#fff",
              fontSize: vertical ? 96 : 84,
              fontWeight: 700,
              lineHeight: 1.1,
              letterSpacing: "-0.02em",
            }}
          >
            {onScreen}
          </div>
        ) : null}
        <div
          style={{
            color: "#C9CCD2",
            fontSize: vertical ? 46 : 38,
            lineHeight: 1.45,
            marginTop: onScreen ? 28 : 0,
            maxWidth: vertical ? "100%" : "80%",
          }}
        >
          {direction}
        </div>
        <div
          style={{
            width: 84, height: 6, backgroundColor: RED,
            marginTop: 34, borderRadius: 3,
          }}
        />
      </div>
      <Caption text={caption} vertical={vertical} />
    </AbsoluteFill>
  );
};

export const SceneReel: React.FC = () => {
  const { durationInFrames } = useVideoConfig();
  const per = Math.floor(durationInFrames / data.slides.length);
  return (
    <AbsoluteFill style={{ backgroundColor: INK }}>
      {/* Storyboard rails: calm conversational read; bed never swells at CTA.
          Both tracks are generated by scripts/ (SAPI VO + soft bed), not hand-edited. */}
      <Audio src={staticFile("vo.wav")} volume={0.95} />
      <Audio src={staticFile("bed.wav")} volume={0.18} />
      {data.slides.map((s, i) => (
        <Sequence key={i} from={i * per} durationInFrames={per}>
          <Slide direction={s.direction} onScreen={s.onScreen} />
        </Sequence>
      ))}
    </AbsoluteFill>
  );
};
